[config]
schemaVersion = "0.0.1"

[package]
namespace = "skytech6"
name = "CrimsonFOV"
versionNumber = "1.0.0"
description = "Modifies the client camera field of view"
websiteUrl = "https://github.com/SkyTech6/CrimsonDropRate/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["gloomrot-update", "mods", "client"]